#!/bin/sh
# 
# 2009      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Add an DNS A entry
#

if [ $# -ne 2 ]; then
   echo "Usage: $0 <name> <ipv4addr>"
   exit 1
fi

name="$1"; shift
ipaddr="$1"; shift

# From config
from_name="Nico Schottelius"
from_mail="nico.schottelius@inf.ethz.ch"
to_mail="helpdesk@id.ethz.ch"
to_name="Technische Hilfe (ID)"

# Send with BCC to us
cat << msgend | /usr/sbin/sendmail -f "$from_mail" "$from_mail" "$to_mail" 
From: "$from_name" <$from_mail>
To: "$to_name" <$to_mail>
X-Sexy: totally!
Subject: DNS-Aenderung

Hallo!

Könnt ihr bitte folgende Anpassung im DNS vornehmen:

- Den A-Eintrag "${name}.inf.ethz.ch" auf "${ipaddr}" einrichten

Beste Grüße,

Nico Schottelius

msgend
