#!/bin/sh
# 
# 2009      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Setup an a-entry via curl to ETH ID Webservice
#

set -e
. "$(which "sexy-config-load")"
. "${__sexy_abs_mydir}/helper-config-load"

ttl="$(sexy_file_read "${sexy_my_config}/ttl")"
isg_group="$(sexy_file_read "${sexy_my_config}/isg_group")"

sexy_args fqdn ipv4a -- "$@"

set -x
curl --request POST $curl_stdin "${komcenter_url_base}/nameToIP" << eof
<insert>
  <nameToIP>
    <ip>${ipv4a}</ip>
    <fqName>${fqdn}</fqName>
    <forward>Y</forward>
    <reverse>N</reverse>
    <ttl>${ttl}</ttl>
    <isgGroup>${isg_group}</isgGroup>
  </nameToIP>
</insert>
eof
