#!/bin/sh
# 
# 2009      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Generate host entries for subnet.conf
#

. "$(which sexy-config-load)"

sexy_args network host -- "$@" 

tmp="$(sexy_shared_temp)-${network}"

# check that the objects exist
if ! sexy_object_exists networks ${network}; then sexy_errormsg "Network $network does not exist"; fi
if ! sexy_object_exists hosts ${host}; then sexy_errormsg "Host $host does not exist"; fi

ipv4a="$(sexy-get hosts ${host} ipv4a)"
mac="$(sexy-get hosts ${host} mac)"

echo "   host ${host} { hardware-ethernet $mac; fixed address $ipv4a; }" >> "${tmp}"

cat "${tmp}"
