#!/bin/sh
# 
# 2009      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Make sure all hosts exists in the external databases, as we like it!
#
#

set -e

################################################################################
# standard vars stolen from cconf
__pwd="$(pwd -P)"
__mydir="${0%/*}"; __abs_mydir="$(cd "$__mydir" && pwd -P)"
__myname=${0##*/}; __abs_myname="$__abs_mydir/$__myname"

. "${__mydir}/sexy-config-load"


# if something was supplied, we take stdin as the changes, otherwise we compare the
# db with reality. FIXME: patch has not yet been implemented.
[ $# -gt 0 ] && patch="-p"

# no hosts base? nothing to do!
cd "${sexy_db_hosts}" || exit 0

set -x

for host in *; do
   # check that there is a network for the configured ip-address is available
   ipv4a="$(sexy-get hosts ${host} ipv4a)"


#   network=$(sexy-network-find $(sexy-host-get-ipv4a))

   # check that ip-address and mac are configured for the host

   # check ip-address assignment (dhcp/static)
   
   # check name assignments (dns):
   # - select correct backend
   # 
   # - check a-entry
   # - check ptr-entry
   # - check all cnames
   # 
   # 
   # 
   # 
   # 
   # 
   # 
   # 
   # 

done
