#!/bin/sh
# 
# 2009-2011 Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Definitely create a dns ptr+a entry
#

. sexy-config

__sexy_args fqdn ipv4a -- "$@" 

# We cannot be sure what the current state is without
# parsing a lot of XML. Thus we CREATE a know state:
# The one that the host does NOT EXIST.
# After that, we recreate it, so we have a consistent state

# FIXME: also ensure that the a-record does not exist on
# another ip address!

"${__sexy_abs_mydir}/libexec/del-a" "${ipv4a}"
"${__sexy_abs_mydir}/libexec/add-a+ptr" "${fqdn}" "${ipv4a}"
