#!/bin/sh
# 
# 2011      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Set first or last usable macaddress (works for both)
#

. sexy-config
. sexy-args -atleast mac -- "$@"
. "$__sexy_plugin_dir/helper"

name="${__sexy_plugin_action#set-}"
file="$(__sexy_plugin_datadir)/$name"

[ -e "${file}" ] && __sexy_exit_err "${file} already exists"

echo $mac > "$file"
