#!/bin/sh
# 
# 2009      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Generate host entries for subnet.conf
#

. "$(which sexy-config-load)"

sexy_args network fqdn -- "$@" 

tmp="$(sexy_shared_temp "${network}")"

# check that the objects exist
if ! sexy_object_exists networks ${network}; then sexy_errormsg "Network $network does not exist"; fi
# check that the fqdn is part of the network
if ! sexy_object_attribute_exists networks ${network} ${fqdn}; then
   sexy_errormsg "Host $fqdn does not exist in $network"
fi

ipv4a="$(sexy-attribute-get networks "${network}" "${fqdn}/ipv4a")"
mac="$(sexy-attribute-get networks "${network}" "${fqdn}/mac")"
next_server="$(sexy-attribute-get networks "$network" "${fqdn}/next-server" failok)"
bootfilename="$(sexy-attribute-get networks "$network" "${fqdn}/bootfilename" failok)"
host="$(echo "${fqdn}" | sed 's/\..*//')"

line="   host ${host} { hardware ethernet $mac; fixed-address $ipv4a;"
[ "${next_server}" ] && line="${line} next-server $next_server;"
[ "${bootfilename}" ] && line="${line} filename \"${bootfilename}\";"
line="${line} }"

echo "${line}" >> "${tmp}"

# debug
#cat "${tmp}"
