#!/bin/sh
# 
# 2009      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Generate footer for subnet.conf
#

. "$(which sexy-config-load)"

sexy_args network -- "$@" 

tmp="$(sexy_shared_temp "${network}")"

# check that the network exists

cat << eof >> "${tmp}"

} # close group
} # }}}
# vim: foldmethod=marker expandtab autoindent tabstop=3 shiftwidth=3 softtabstop=3
eof
