#!/bin/sh
# 
# 2009      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Add an DNS A entry
#

if [ $# -ne 2 ]; then
   echo "Usage: $0 <name> <ipv4addr>"
   exit 1
fi

name="$1"; shift
ipaddr="$1"; shift

cat << msgend | /usr/sbin/sendmail -f nico.schottelius@inf.ethz.ch nico.schottelius@inf.ethz.ch asteven@inf.ethz.ch
From: Nico Schottelius <nico.schottelius@inf.ethz.ch>
To: Technische Hilfe <helpdesk@id.ethz.ch>
CC: pseudo-cc@nowhere, asteven
X-Sexy: totally!
Subject: DNS-Aenderung

## sollte in ein header
Hallo!

Könnt ihr bitte folgende Anpassung im DNS vornehmen:

## sollte in ein header (ENDE)

- Den A-Eintrag "${name}.inf.ethz.ch" auf "${ipaddr}" einrichten

## sollte in einen footer / konfiguration

Beste Grüße,

Nico Schottelius

msgend
