#!/bin/sh
# 
# 2009      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Add a cname-entry via curl to ETH ID Webservice
#
 

[ $# -eq 2 ] || exit 1

set -x

fqdn="$1";shift
cname="$1";shift

cat << eof | curl --basic --netrc --insecure --request POST --header "Content-Type: text/xml" --data @- https://www.komcenter.ethz.ch/ip/rest/alias
<insert>
  <alias>
    <fqName>${cname}</fqName>
    <hostName>${fqdn}</hostName>
    <ttl>600</ttl>
  </alias>
</insert>
eof
