#!/bin/sh
# 
# 2009      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Delete an IPN ETH ID Webservice
#

echo "I am not sure, what this thingy really deletes"

[ $# -eq 1 ] || exit 1

set -e

. "$(which "sexy-config-load")"
. "${__sexy_abs_mydir}/helper-config-load"

ipv4a="$1";shift

set -x

curl --request DELETE "${komcenter_url_base}/nameToIP/${ipv4a}"
