#!/bin/sh
#
# Add a new database entry.
#

. sexy-config
. lib/db-config

. sexy-args -atleast name id -- "$@"

__db_check_id "$name" || __sexy_exit_err "Invalid database name: $name"
__db_check_id "$id" || __sexy_exit_err "Invalid database id: $id"

db_dir="$name/$id"
mkdir -p "$db_dir"

sexy db set $name $id $@

