#!/bin/sh
#
# Sexy generic add.
#
#

. sexy-config
. lib/db-config

name="$1"; shift
__db_check_id "$name" || __sexy_exit_err "Invalid database name: $name"

id="$1"; shift
__db_check_id "$id" || __sexy_exit_err "Invalid database id: $id"


db_dir="$name/$id"
mkdir -p "$db_dir"

sexy db set $name $id $@
exit 0

# Each longopt argument is a property name
while [ "$#" -gt "0" ]; do
   if echo "$1" | grep -q '^--'; then
      __db_check_id "$1" || __sexy_exit_err "Invalid property name: $1"
      key=$(echo $1 | sed 's|^--||')
      touch "$key"
   else
      [ -n "$key" ] || __sexy_exit_err "Unnamed property value"
      value="$1"
      echo "$value" > "$key"
      key=
   fi
   shift
done

