#!/bin/sh
#
# Delete an entry from a sexy database.
#

. sexy-config
. lib/db-config

. sexy-args -atleast name id -- "$@"

__db_check_id "$name" || __sexy_exit_err "Invalid database name: $name"
__db_check_id "$id" || __sexy_exit_err "Invalid or missing database id: $id"

rm -rf "$name/$id"

