#!/bin/sh
#
# Get one or more properties from an existing database entry.
#

. sexy-config
. lib/db-config

. sexy-args -atleast name id -- "$@"

__db_check_id "$name" || __sexy_exit_err "Invalid database name: $name"
[ -d "$name" ] || __sexy_exit_err "No such database: $name"

__db_check_id "$id" || __sexy_exit_err "Invalid database id: $id"

db_dir="$name/$id"
[ -d "$db_dir" ] || __sexy_exit_err "No such database entry: $db_dir"

cd "$db_dir"

# TODO: discuss if get should only return a single value per call or multiple,
#  as the current implementation does
while [ "$#" -gt "0" ]; do
   if echo "$1" | grep -q '^--'; then
      __db_check_id "$1" || __sexy_exit_err "Invalid property name: $1"
      key=$(echo $1 | sed 's|^--||')
      echo "$key: $(cat "$key")"
   fi
   shift
done

