#!/bin/sh
#
# List all ids in a database.
#

. sexy-config
. lib/db-config

. sexy-args -atleast name -- "$@"

__db_check_id "$name" || __sexy_exit_err "Invalid database name: $name"
[ -d "$name" ] || __sexy_exit_err "No such database: $name"

cd "$name" && ls -1

