#!/bin/sh

. sexy-config

cat << EOF
Help! is the title of the fifth British and ninth American album by The Beatles, and the soundtrack from their film of the same name. Produced by George Martin for EMI's Parlophone Records, it contains fourteen songs in its original British form, of which seven appeared in the film Help!. These songs took up the first side of the vinyl album and included the singles "Help!" and "Ticket to Ride". The second side contained seven other releases including the most covered song ever written, "Yesterday".

The American release was a true soundtrack album, mixing the first seven songs with orchestral material from the film. Of the other seven songs which were on the British release, two were released on the US version of the next Beatles album, Rubber Soul, two were back-to-back on the next US single and then appeared on Yesterday and Today and three had already been on Beatles VI.

In 2003, the album was ranked number 332 on Rolling Stone magazine's list of the 500 greatest albums of all time.
EOF
