#!/bin/sh
#
# Sexy generic add.
#
#

error() {
   echo "[ERROR] $@" >&2
}

die() {
   error "$@"
   exit 1
}


id="$1"; shift

# FIXME: find a better definiton of sane (i.e. everything that is a valid filename)
sanechars='[A-Za-z0-9_]'

mkdir "$id"
pushd "$id" > /dev/null

# while [ $# -gt 0 ]; do
   # opt="$1"; shift
# 
   # echo "$opt" | grep -q "^--${sanechars}*\$" || die "Invalid property name: $opt"
# 
   # opt_file="$(echo $opt | sed 's/^--//')"
# 
   # [ $# -ge 1 ] || die "Missing value for $opt"
# 
   # value="$1"; shift
# 
   # echo "${value}" > "${opt_file}"
# 
# done

while [ "$#" -gt "0" ]; do
   if echo "$1" | grep -q '^--'; then
      echo "$1" | grep -q "^--${sanechars}*\$" || die "Invalid property name: $1"
      key=$(echo $1 | sed 's|^--||')
      touch "$key"
   else
      [ -n "$key" ] || die "Unnamed property value"
      value="$1"
      echo "$value" > "$key"
      key=
   fi
   shift
done

popd > /dev/null

