#!/bin/sh
# 
# 2009      Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Add a host (and do all the stuff depending on it)
#

set -e

. "$(which sexy-config-load)"

sexy_args -atleast network fqdn -- "$@"
sexy_args -skip -optional address -- "$@"

if ! sexy_object_exists networks "${network}"; then
   sexy_errormsg "Network $network does not exist"
fi
if ! sexy_object_exists hosts "${fqdn}"; then
   sexy_errormsg "Host $fqdn does not exist"
fi

# if address was not specified, use next free one
[ "${address}" ] || address="$(sexy-network-free-address-get "${network}")"

hostinnetwork="$(sexy_object_path networks "${network}")/${fqdn}"
ln -s "../../hosts/${fqdn}" "${hostinnetwork}"

echo "${address}" > "${hostinnetwork}/ipv4a"
