#!/bin/sh
# 
# 2009-2011 Nico Schottelius (nico-sexy at schottelius.org)
# 
# This file is part of sexy.
#
# sexy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# sexy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with sexy. If not, see <http://www.gnu.org/licenses/>.
#
#
# Helper for ETH DNS ID WS
#

alias curl="curl -s -S --basic --netrc --insecure --header \"Content-Type: text/xml\""
curl_xmlheader="--header \"Content-Type: text/xml\""
curl_stdin="--data @-"

komcenter_url_base="https://www.komcenter.ethz.ch/ip/rest"

result_filter="grep Done"


