#!/bin/sh
set -e
. "$(which sexy-config-load)"
set +e

#set -x
for i in $(seq 8 32); do
   echo -n $i :
   sexy_network_decimal_netmask $i
done
set +x
sexy_network_decimal_broadcast 10.110.128.0 17
sexy_network_decimal_broadcast 192.168.42.0 24
sexy_network_decimal_broadcast 192.168.42.0 25
